apiVersion: v1
kind: Secret
metadata:
  name: thanos-config
  namespace: monitoring
type: Opaque
stringData:
  remote_storage.yml: |
    # https://thanos.io/storage.md/#configuration
    type: S3
    config:
      bucket: ""
      endpoint: ""
      access_key: ""
      secret_key: ""
      #region: ""
      #insecure: false
      #signature_version2: false
      #encrypt_sse: false
      #put_user_metadata: {}
      #http_config:
      #  idle_conn_timeout: 90s
      #  response_header_timeout: 2m
      #  insecure_skip_verify: false
      #trace:
      #  enable: false
      #part_size: 134217728
